server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /login {
        return 302 ${LOGIN_URL}/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
            chunked_transfer_encoding off;
        resolver 127.0.0.11:53 valid=30s;
        set $upstream ${API_UPSTREAM};


        proxy_pass $upstream;
        proxy_http_version 1.1;
        proxy_set_header Transfer-Encoding "";

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}